workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

image: node:20-alpine

run_tests:
  tags:
    - kvm
    - docker
  stage: test
  only:
    - master
  before_script:
    - echo "preparing test data ..."
    - npm version
  script:
    - echo "running test...."
  after_script:
    - echo "clean up temporary files..."


build_image:
  tags:
    - shell-exec
  stage: build
  #image: alpine
  script:
    - echo "building state"
    - sleep 20

push_image:
  tags:
    - shell-exec
  stage: build
  needs:
    - build_image
  #image: alpine
  script:
    - echo "push stage"


deploy_image: 
  tags: 
    - shell-exec
  stage: deploy
  script: 
    - echo "deploying in deploy stage ..."
