workflow:
  rules:
    - if $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy


run_tests:
  tags:
    - kvm
    - docker
  stage: test
  before_script:
    - echo "preparing test data ..."
  script:
    - echo "running test...."
  after_script:
    - echo "clean up temporary files..."


build_image:
  tags:
    - shell-exec
  stage: build
  #image: alpine
  script:
    - echo "building state"
    - sleep 20

push_image:
  tags:
    - shell-exec
  stage: build
  needs:
    - build_image
  #image: alpine
  script:
    - echo "push stage"


deploy:
  tags:
    - shell-exec
  stage:
    - deploy
  script:
    - echo "deploying in deploy stage"
