run_tests:
    tags:
        - kvm
        - docker
    before_script:
        - echo "preparing test data ..."
    script:
        - echo "running test...."
    after_script:
        - echo "clean up temporary files..."
